# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170810_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='위도/경도 포맷으로 입력해 주세여', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='포스팅 제목을 설정해 주세요, 최대 100자 내로 써주세요', max_length=100, verbose_name='제목'),
        ),
    ]
