# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 06:14
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170810_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도/위도 포맷으로 입력해 주세여', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
